### PR TITLE
Add pointOfInterestFilter and fix region initialization

### PR DESCRIPTION
**Pull request by RemiBardon**

### CODE REVIEW

**Comment by RemiBardon** [comment]
I just realized I committed to my `master` branch, they have been added to the PR. I wanted to merge them anyway 💁🏻‍♂️

**Comment by sgade** [comment]
Hi @RemiBardon, thanks for your PR.

Unfortunately, in this state I cannot merge the changes. Having a clear goal on what you are aiming for both in prose and code is important. Would be please be so kind to update your code in the following ways:

1. Add a description for what this PR is changing and why. Point to important places that I should focus my review on.
2. Please avoid whitespaces changes or other automatic changes by your editor. This makes change sets harder to review and adds unwanted clutter.
3. If there are changes that you would like to get merged but that are not related to the primary goal in the PR, please separate them out into separate PRs. Those PRs should adhere to to the same standards as listed above.

If you have any questions, feel free to ask. Once you are done, add me as a reviewer and leave a comment to indicate that you are done. Please try to avoid pushing too many times, though.

**Comment by sgade** [comment]
@RemiBardon Closing because of inactivity. Would love to see you work on this PR and reopen it.

**Comment by RemiBardon** [comment]
@sgade Sorry for the inactivity, I'm busy on a lot of things rn 😕 I'll come back with a better PR next time 😉

**Pull request closed without merging**
